services:
  app:
    build: .
    ports:
      - "7777:7777"
    env_file:
      - .env
    environment:
      - DOCKER=true
    volumes:
      - ./tmp:/app/tmp
      - ./videos:/app/videos
      - ./transcriptions.json:/app/transcriptions.json
    restart: unless-stopped
